AWSTemplateFormatVersion: "2010-09-09"

Description: "Central Persistence"

Resources:
  ECRKolvir:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: kolvir
Outputs:
  ECRKolvirArn:
    Value: !GetAtt ECRKolvir.Arn
  ECRKolvirUri:
    Value: !GetAtt ECRKolvir.RepositoryUri
