AWSTemplateFormatVersion: "2010-09-09"

Description: "Central Persistence"

Resources:
  ECRKolvir:
    Type: AWS::ECR::Repository
Outputs:
  ECRArn:
    Value: !GetAtt ECRKolvir.Arn
  ECRUri:
    Value: !GetAtt ECRKolvir.RepositoryUri
